### ISSUE TITLE
Expand Ansible Collection to include Conjur Role

### ISSUE THREAD

**Issue by izgeri** [cyberark/ansible-conjur-collection#42]
- [x] Inclusion of cyberark.conjur in Ansible 2.10 - #30
- [x] Migrate this Ansible role to the Conjur Ansible collection - cyberark/ansible-conjur-host-identity#30
- [x] There is a new tag of ansible-conjur-host-identity to announce deprecation of standalone project  - cyberark/ansible-conjur-host-identity#42
- [x] ansible-conjur-host-identity docs are migrated - cyberark/ansible-conjur-host-identity#36
- [ ] Ansible documentation is updated - cyberark/conjur-docs#1015 
- [x] There is a new release of ansible-conjur-collection - #35
- [ ] There is a demo showing how to use this collection - #37
